### ISSUE TITLE
Create Login Page and Route

### ISSUE THREAD

**Issue by nayanjaiswalgit** [nayanjaiswalgit/foci#4]
Overview
We need to create a frontend route and page for user login. This page will allow users to enter their credentials to access their accounts.

Requirements
Login Page: Form for users to log into their accounts.
Route: Define the route for the login page.
Steps to Implement
Design Login Page: Create a user-friendly interface for the login page.
Create Route: Define the route /login in the frontend.
Implement Form: Create and implement a login form with necessary validation.
Integrate Backend: Connect the form to the backend API to handle login authentication.
Error Handling: Implement proper error handling and user feedback mechanisms.
Test: Thoroughly test the login page and form to ensure it works as expected.

**Comment by ayushsonone07** [comment]
Complete ✔
