### ISSUE TITLE
Create Signup Page and Route

### ISSUE THREAD

**Issue by nayanjaiswalgit** [nayanjaiswalgit/foci#7]
####Overview
We need to create a frontend route and page for user signup. This page will allow users to create a new account.

#### Requirements
- **Signup Page**: Form for users to create a new account.
- **Route**: Define the route for the signup page.

#### Steps to Implement
1. **Design Signup Page**: Create a user-friendly interface for the signup page.
2. **Create Route**: Define the route `/signup` in the frontend.
3. **Implement Form**: Create and implement a signup form with necessary validation.
4. **Integrate Backend**: Connect the form to the backend API to handle user registration.
5. **Error Handling**: Implement proper error handling and user feedback mechanisms.
6. **Test**: Thoroughly test the signup page and form to ensure it works as expected.

**Comment by ayushsonone07** [comment]
Complete ✔
